In [15]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

import nltk
import re
from sklearn.model_selection import train_test_split

from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score, classification_report

In [ ]:
data = {
    "ticket": [
        "My account is not working",
        "Payment failed during transaction",
        "I forgot my password",
        "Internet connection is very slow",
        "Need refund immediately",
        "App crashes every time I open",
        "My order has not arrived",
        "How can I change my email",
        "Money deducted but transaction failed",
        "Service is not available"
    ],

    "priority": [
        "high",
        "high",
        "medium",
        "medium",
        "high",
        "medium",
        "high",
        "low",
        "high",
        "medium"
    ]
}


df = pd.DataFrame(data)

df

                                  ticket priority
0              My account is not working     high
1      Payment failed during transaction     high
2                   I forgot my password   medium
3       Internet connection is very slow   medium
4                Need refund immediately     high
5          App crashes every time I open   medium
6               My order has not arrived     high
7              How can I change my email      low
8  Money deducted but transaction failed     high
9               Service is not available   medium

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ticket    10 non-null     object
 1   priority  10 non-null     object
dtypes: object(2)
memory usage: 292.0+ bytes

In [ ]:
df.isnull().sum()

ticket      0
priority    0
dtype: int64

In [ ]:
def clean_text(text):

    text = text.lower()

    text = re.sub('[^a-zA-Z]', ' ', text)

    return text


df['clean_ticket'] = df['ticket'].apply(clean_text)

df.head()

,ticket,priority,clean_ticket
0,My account is not working,high,my account is not working
1,Payment failed during transaction,high,payment failed during transaction
2,I forgot my password,medium,i forgot my password
3,Internet connection is very slow,medium,internet connection is very slow
4,Need refund immediately,high,need refund immediately

In [ ]:
X = df['clean_ticket']

y = df['priority']


X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
vectorizer = TfidfVectorizer()

X_train = vectorizer.fit_transform(X_train)

X_test = vectorizer.transform(X_test)

In [ ]:
model = LogisticRegression()


model.fit(
    X_train,
    y_train
)

LogisticRegression()

In [ ]:
y_pred = model.predict(X_test)

y_pred

array(['medium', 'medium'], dtype=object)

In [ ]:
accuracy = accuracy_score(
    y_test,
    y_pred
)


print("Accuracy:",accuracy)

Accuracy: 0.0

In [ ]:
print(
classification_report(
    y_test,
    y_pred
)
)

              precision    recall  f1-score   support

        high       0.00      0.00      0.00       2.0
      medium       0.00      0.00      0.00       0.0

    accuracy                           0.00       2.0
   macro avg       0.00      0.00      0.00       2.0
weighted avg       0.00      0.00      0.00       2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
new_ticket = [
    "My money was deducted and I need help"
]


new_ticket = vectorizer.transform(new_ticket)


prediction = model.predict(new_ticket)


print("Priority:",prediction[0])

Priority: high

In [14]:
import pickle
pickle.dump(
    model,
    open("ticket_classifier.pkl","wb")
)


pickle.dump(
    vectorizer,
    open("tfidf_vectorizer.pkl","wb")
)